# Generated by Django 5.2.15 on 2026-09-30 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0122_alter_draftissue_assignees_alter_issue_assignees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='calendar_system',
            field=models.CharField(choices=[('gregorian', 'Gregorian'), ('persian', 'Persian')], default='gregorian', max_length=16),
        ),
    ]
