# Generated by Django 5.2.15 on 2026-10-04 01:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0123_profile_calendar_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bale_chat_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.CreateModel(
            name='NotificationChannelLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('BALE', 'Bale')], max_length=20)),
                ('event', models.CharField(choices=[('property_change', 'Property change'), ('state_change', 'State change'), ('comment', 'Comment'), ('mention', 'Mention'), ('issue_completed', 'Issue completed')], max_length=30)),
                ('entity_identifier', models.UUIDField(null=True)),
                ('entity_name', models.CharField(max_length=255)),
                ('data', models.JSONField(null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('error_message', models.CharField(blank=True, default='', max_length=255)),
                ('processed_at', models.DateTimeField(null=True)),
                ('sent_at', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_notifications', to=settings.AUTH_USER_MODEL)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='triggered_channel_notifications', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Notification Channel Log',
                'verbose_name_plural': 'Notification Channel Logs',
                'db_table': 'notification_channel_logs',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['channel', 'processed_at', 'status'], name='notif_channel_queue_idx'), models.Index(fields=['receiver', 'channel', 'created_at'], name='notif_channel_receiver_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationChannelPreference',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('BALE', 'Bale')], max_length=20)),
                ('event', models.CharField(choices=[('property_change', 'Property change'), ('state_change', 'State change'), ('comment', 'Comment'), ('mention', 'Mention'), ('issue_completed', 'Issue completed')], max_length=30)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_channel_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Channel Preference',
                'verbose_name_plural': 'Notification Channel Preferences',
                'db_table': 'notification_channel_preferences',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('user', 'channel', 'event'), name='uniq_notification_channel_preference')],
            },
        ),
        migrations.CreateModel(
            name='UserNotificationChannel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('BALE', 'Bale')], max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], max_length=20, null=True)),
                ('last_delivered_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_channels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Notification Channel',
                'verbose_name_plural': 'User Notification Channels',
                'db_table': 'user_notification_channels',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('user', 'channel'), name='uniq_user_notification_channel')],
            },
        ),
    ]
