# Generated by Django 5.2.15 on 2026-10-04 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0124_user_bale_chat_id_notificationchannellog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='text_direction',
            field=models.CharField(choices=[('rtl', 'Right-to-left'), ('ltr', 'Left-to-right')], default='rtl', max_length=3),
        ),
    ]
