# Generated by Django 5.2.15 on 2026-10-04 15:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0125_profile_text_direction'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationChannelPairingCode',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('BALE', 'Bale')], default='BALE', max_length=20)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_chat_id', models.CharField(blank=True, max_length=128, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_channel_pairing_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Channel Pairing Code',
                'verbose_name_plural': 'Notification Channel Pairing Codes',
                'db_table': 'notification_channel_pairing_codes',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['channel', 'expires_at'], name='notif_pairing_expiry_idx')],
            },
        ),
    ]
