# Generated by Django 5.2.15 on 2026-10-04 16:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('db', '0126_notificationchannelpairingcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_subscriptions', to='db.workspace', verbose_name='Workspace'),
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Feature Flag Code')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('category', models.CharField(blank=True, default='general', max_length=100, verbose_name='Category')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('is_public', models.BooleanField(default=True, verbose_name='Public')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Feature Flag',
                'verbose_name_plural': 'Feature Flags',
                'ordering': ('category', 'code'),
            },
        ),
        migrations.CreateModel(
            name='PlanFeatureFlag',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Config')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('feature_flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_grants', to='billing.featureflag', verbose_name='Feature Flag')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_flags', to='billing.plan', verbose_name='Plan')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Plan Feature Flag',
                'verbose_name_plural': 'Plan Feature Flags',
                'ordering': ('plan__code', 'feature_flag__code'),
                'constraints': [models.UniqueConstraint(fields=('plan', 'feature_flag'), name='unique_plan_feature_flag')],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceFeatureFlag',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_enabled', models.BooleanField(default=False, verbose_name='Enabled')),
                ('enabled_at', models.DateTimeField(blank=True, null=True, verbose_name='Enabled At')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Config')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('enabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enabled_billing_feature_flags', to=settings.AUTH_USER_MODEL, verbose_name='Enabled By')),
                ('feature_flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_activations', to='billing.featureflag', verbose_name='Feature Flag')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_feature_flags', to='db.workspace', verbose_name='Workspace')),
            ],
            options={
                'verbose_name': 'Workspace Feature Flag',
                'verbose_name_plural': 'Workspace Feature Flags',
                'ordering': ('feature_flag__category', 'feature_flag__code'),
                'constraints': [models.UniqueConstraint(fields=('workspace', 'feature_flag'), name='unique_workspace_feature_flag')],
            },
        ),
    ]
